### ISSUE TITLE
Mouse Scroll not working in VM window

### ISSUE THREAD

**Issue by OliverRito** [TriFProgrammer/TriFStreaming#2]
Mouse Scroll not working in VM window

**Comment by TriFProgrammer** [comment]
According to this: https://developer.mozilla.org/en-US/docs/Web/API/Element/DOMMouseScroll_event

"wheel" is the correct event listener, compatible with both Chrome and Firefox.

**Comment by TriFProgrammer** [comment]
This will be fixed in the next release
