### ISSUE TITLE
Audio Not in Stereo

### ISSUE THREAD

**Issue by OliverRito** [TriFProgrammer/TriFStreaming#4]

**Comment by TriFProgrammer** [comment]
According to this bug, it could be an issue with SDP negotiation https://bugs.chromium.org/p/webrtc/issues/detail?id=8133

**Comment by TriFProgrammer** [comment]
Previously the RTP stream going to Janus was mono because of Chrome bug. It will be changed to stereo, the affects will be immediate on Firefox. Chrome users will have to wait until the next release.
