### ISSUE TITLE
Not capturing back-space

### ISSUE THREAD

**Issue by OliverRito** [TriFProgrammer/TriFStreaming#5]
When vm window in-focus with control activate, back-space is not captured. only tested in Firefox.

**Comment by TriFProgrammer** [comment]
I tested this on Firefox myself, it worked for me. I'd be interested to do some debugging if it's easily reproducible on your end.

**Comment by TriFProgrammer** [comment]
On Firefox the backspace key will send a back to the browser, going to the last page. Preventing the default actions on certain keys should mitigate this.
